### Авторизация - получение токена
POST http://localhost:8088/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "pa55w0rd"
}

### Получение кода
GET http://localhost:8088/api/otp/code
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpYXQiOjE2MjU2NjM5MzIuMTUzNTA0LCJleHAiOjE2MjU2NjQ4MzIuMTUzNTQ1LCJ0eXBlIjoiQXBwXFxFbnRpdHlcXFBlcnNvbiIsImlkIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOltdfQ.U8U3qEYLnpHAO_ha5P3YxWxLtbfxYItf3jZnlQCvI1Q6efdenWBqBlnudASYKkv7fPPh2XGMiuBl4CAFCz3hrMEteGgZRf4DgNsEjnaoXmxdMBgSi8QuFgYzSda6nYOLH4W85Xibbq38QjTWzFQhw9wX1rJooGUbhwm9M2nTmuP_QbBiw8jGeMPMHuFevpL5jpEADP87BHrJTXmGDh83XRXDejg9iXTdGRGuGRDUq9J-BezAu1UftPY3OMJrk-GmEHO1QGuwcj4YUXhH-s_WLy_dekm89vdwHoUePwUux5dkpxXI8WSwjjkVpgyt3s7e-ZFsohnFc7z0BlAWNG5JoQ



### Авторизация - Проверка токена
GET http://localhost:8088/api/auth/check
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpYXQiOjE2MjU2NjM5MzIuMTUzNTA0LCJleHAiOjE2MjU2NjQ4MzIuMTUzNTQ1LCJ0eXBlIjoiQXBwXFxFbnRpdHlcXFBlcnNvbiIsImlkIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOltdfQ.U8U3qEYLnpHAO_ha5P3YxWxLtbfxYItf3jZnlQCvI1Q6efdenWBqBlnudASYKkv7fPPh2XGMiuBl4CAFCz3hrMEteGgZRf4DgNsEjnaoXmxdMBgSi8QuFgYzSda6nYOLH4W85Xibbq38QjTWzFQhw9wX1rJooGUbhwm9M2nTmuP_QbBiw8jGeMPMHuFevpL5jpEADP87BHrJTXmGDh83XRXDejg9iXTdGRGuGRDUq9J-BezAu1UftPY3OMJrk-GmEHO1QGuwcj4YUXhH-s_WLy_dekm89vdwHoUePwUux5dkpxXI8WSwjjkVpgyt3s7e-ZFsohnFc7z0BlAWNG5JoQ

### Авторизация - Проверка токена - плохой ключ
GET http://localhost:8088/api/auth/check
Content-Type: application/json
Authorization: Bearer eyggJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpYXQiOjE2MjU2NjM5MzIuMTUzNTA0LCJleHAiOjE2MjU2NjQ4MzIuMTUzNTQ1LCJ0eXBlIjoiQXBwXFxFbnRpdHlcXFBlcnNvbiIsImlkIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOltdfQ.U8U3qEYLnpHAO_ha5P3YxWxLtbfxYItf3jZnlQCvI1Q6efdenWBqBlnudASYKkv7fPPh2XGMiuBl4CAFCz3hrMEteGgZRf4DgNsEjnaoXmxdMBgSi8QuFgYzSda6nYOLH4W85Xibbq38QjTWzFQhw9wX1rJooGUbhwm9M2nTmuP_QbBiw8jGeMPMHuFevpL5jpEADP87BHrJTXmGDh83XRXDejg9iXTdGRGuGRDUq9J-BezAu1UftPY3OMJrk-GmEHO1QGuwcj4YUXhH-s_WLy_dekm89vdwHoUePwUux5dkpxXI8WSwjjkVpgyt3s7e-ZFsohnFc7z0BlAWNG5JoQ

### Авторизация - Обновление токена
POST http://localhost:8088/api/auth/update
Content-Type: application/json
Cookie: refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpYXQiOjE2MjU2NjQyNTkuNDk2ODk4LCJleHAiOjE2MjU3NTA2NTkuNDk2OSwiaWQiOjIsInVzZXJuYW1lIjoiYWRtaW4iLCJyZWZyZXNoIjp0cnVlfQ.2p-FFQLUxU3wJeajkWmk_9POx9g4oL5Ytw7b2pwxTDRLeLlasIoWP-MBM-8JpSsvJKQ7dkuPjkMF4ilc3pk6WAhPWtS331sxDxRVXET3J7BH5u2MEEw9YL0ezxV3ZG-gj69WFC9BBg4zaj4AIM6H2gSRJLwszV-NfK_Bl2XX6rwkhYdasaXN3cRxJeIeJnDjw6vlm12vb75JJOXNoha1-qup8Vie0LzSeKVxumwl7Ja-RrB3fiKzplkAa6GO7TzsMXdARYePlbct8uHQTY4SUKJZAkd61tyre6HJ38p6GE-7aWMyIlyCOdtH3tcszMf_J_RCRc1djcpjPviupag3gg;

### Авторизация - Обновление токена, невалидный refresh токен
POST http://localhost:8088/api/auth/update
Content-Type: application/json
Cookie: refresh-token=312312

### Авторизация - Выход
POST http://localhost:8088/api/auth/logout
Content-Type: application/json
