# docker/docker-compose.yml
version: '3'

networks:
  backend:
  frontend:
  socket:
  api:
  broker:

services:

  database:
    container_name: database-two
    build:
      context: ./docker/database
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_PORT=${DATABASE_PORT}
    volumes:
      - ./docker/database/data:/docker-entrypoint-initdb.d
      - ./docker/database/mysql:/var/lib/mysql
    networks:
      - backend

  php-cli:
    container_name: php-cli-two
    build:
      context: ./docker/php-cli
      args:
        UID: ${UID}
        GID: ${GID}
    stdin_open: true
    tty: true
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=${DATABASE_SERVER_VERSION}
      - WAIT_HOSTS=database:${DATABASE_PORT}
    volumes:
      - ./app:/var/www
    networks:
      - backend

  php-fpm:
    container_name: php-fpm-two
    build:
      context: ./docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=${DATABASE_SERVER_VERSION}
    volumes:
      - ./app:/var/www
    networks:
      - backend
      - api

  nginx:
    container_name: nginx-two
    build:
      context: ./docker/nginx
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php-fpm
    environment:
      - WAIT_HOSTS=php-fpm:9000
    ports:
      - "8088:80"
    networks:
      - api
